### ISSUE TITLE
Setup the Firebase project

### ISSUE THREAD

**Issue by loque** [gonzalo-s/180-consultora#4]
1. Create the `Firebase` project ([docs](https://firebase.google.com/docs/web/setup#create-firebase-project)).
2. Register the app with Firebase ([docs](https://firebase.google.com/docs/web/setup#register-app)).
3. Add `Firebase SDK`s and initialize `Firebase` in a file `firebase.js`, including the configuration because it is [considered public](https://firebase.google.com/docs/projects/learn-more#config-files-objects) ([docs](https://firebase.google.com/docs/web/setup#add-sdks-initialize)).

**Comment by gonzalo-s** [comment]
Firebase initialized in file: firebase.js
commit: 65cc22647bffab00b5cdb89550da7ed8bdaa2b30
